### ISSUE TITLE
Potentially lost inexhaustible information

### ISSUE THREAD

**Issue by onecrayon** [patrickdemooij9/AshesCardBot#1]
Looks pretty good! This line, however, is losing some potentially important information for Ashes cards:

https://github.com/patrickdemooij9/AshesCardBot/blob/210a8703e8ebbb18eda4e38fb2eb5fdd3b9313ea/RedditBotClass.py#L159

The formatting for text on Ashes.live for cards uses `*` prefixing a line to represent a line that is inexhaustible; e.g. see https://ashes.live/cards/archasaurus-mount/

This is important information for evaluating the card because inexhaustible abilities are always active (whereas all others get blanked as soon as the card exhausts). I'm not sure how best to represent this on Reddit, but it absolutely needs to be called out somehow.

Similarly, there's an additional prefix `~` that you are not currently accounting for, which represents "reaction abilities"; e.g. see https://ashes.live/cards/shadow-guard/

These are similar to inexhaustible abilities, except they allow the card to be played as a reaction instead of at normal speed.

Thanks for making this tool!

**Comment by patrickdemooij9** [comment]
Hi @onecrayon,

Thanks for checking out the tool! I was indeed looking at what the * was in the rule book, but couldn't find it at the moment. So thank you for the explanation. I have added extra formatting for these cases! 

Also thanks a lot for making ashes.live. It makes this tool a lot easier to make.
